# Generated by Django 5.2.7 on 2026-01-24 15:14

import django.db.models.deletion
import plants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0003_remove_field_irrigation_date_alter_field_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('wheat', 'Buğda'), ('corn', 'Qarğıdalı'), ('barley', 'Arpa'), ('sunflower', 'Günəbaxan'), ('cotton', 'Pambıq'), ('tomato', 'Pomidor'), ('potato', 'Kartof'), ('other', 'Digər')], max_length=20, verbose_name='Bitki növü')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='Sort')),
                ('planting_date', models.DateField(verbose_name='Əkmə tarixi')),
                ('expected_harvest_date', models.DateField(blank=True, null=True, verbose_name='Gözlənilən yığım tarixi')),
                ('actual_harvest_date', models.DateField(blank=True, null=True, verbose_name='Həqiqi yığım tarixi')),
                ('growth_stage', models.CharField(choices=[('seedling', 'Cücərti'), ('vegetative', 'Vegetativ'), ('flowering', 'Çiçəkləmə'), ('fruiting', 'Meyvə'), ('mature', 'Yetişmiş'), ('harvested', 'Yığılmış')], default='seedling', max_length=20, verbose_name='Böyümə mərhələsi')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sahə (hektar)')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('harvested', 'Yığılıb'), ('failed', 'Uğursuz'), ('diseased', 'Xəstə')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('image', models.ImageField(blank=True, help_text='Bitkiin şəklini yükləyin (max 5MB)', null=True, upload_to=plants.models.Plant.plant_image_path, verbose_name='Şəkil')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='fields.field', verbose_name='Sahə')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
    ]
