# Generated by Django 5.2.7 on 2025-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy'), ('silty', 'Silty'), ('peat', 'Peat')], default='loamy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
