# Generated by Django 5.2.7 on 2025-11-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_date', models.DateField(verbose_name='Hava tarixi')),
                ('temperature_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maksimum temperatur (°C)')),
                ('temperature_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum temperatur (°C)')),
                ('temperature_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Orta temperatur (°C)')),
                ('humidity_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Orta rütubət (%)')),
                ('humidity_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maksimum rütubət (%)')),
                ('humidity_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum rütubət (%)')),
                ('precipitation_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Yağıntı (mm)')),
                ('wind_speed_avg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Orta külək sürəti (m/s)')),
                ('wind_speed_max', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maksimum külək sürəti (m/s)')),
                ('wind_direction_degrees', models.IntegerField(blank=True, null=True, verbose_name='Külək istiqaməti (dərəcə)')),
                ('solar_radiation_mj_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Günəş radiasiyası (MJ/m²)')),
                ('evapotranspiration_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Evapotranspirasiya (mm)')),
                ('weather_condition', models.CharField(choices=[('sunny', '☀️ Günəşli'), ('cloudy', '☁️ Buludlu'), ('rainy', '🌧️ Yağmurlu'), ('stormy', '⛈️ Tufanlı'), ('foggy', '🌫️ Dumanlı'), ('snowy', '❄️ Qarlı'), ('windy', '💨 Küləkli')], max_length=20, verbose_name='Hava şəraiti')),
                ('data_source', models.CharField(default='api', max_length=50, verbose_name='Məlumat mənbəyi')),
                ('forecast_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Proqnoz dəqiqliyi (%)')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='fields.field')),
            ],
            options={
                'verbose_name': 'Hava məlumatı',
                'verbose_name_plural': 'Hava məlumatları',
                'ordering': ['-weather_date'],
                'unique_together': {('field', 'weather_date')},
            },
        ),
    ]
