# Generated by Django 5.2.7 on 2025-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_avg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Orta rütubət (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Maksimum rütubət (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_min',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Minimum rütubət (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='precipitation_mm',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Yağıntı (mm)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature_avg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Orta temperatur (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Maksimum temperatur (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature_min',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Minimum temperatur (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed_avg',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Orta külək sürəti (m/s)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed_max',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Maksimum külək sürəti (m/s)'),
        ),
    ]
