# Generated by Django 5.2.7 on 2026-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherdata_humidity_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_avg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Orta hava rütubəti (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Maks. hava rütubəti (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_min',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Min. hava rütubəti (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction_degrees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Külək istiqaməti (°)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed_avg',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Orta külək (m/s)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed_max',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Maks. külək (m/s)'),
        ),
    ]
