# Generated by Django 5.2.7 on 2026-03-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
