# Generated by Django 5.2.7 on 2026-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usersession_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={},
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='last_login',
            new_name='last_activity',
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
