# Generated by Django 5.2.7 on 2026-03-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='last_activity',
            new_name='last_login',
        ),
    ]
