# Generated by Django 5.2.7 on 2025-10-25 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Məhsul adı')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='Məhsul kodu')),
                ('category', models.CharField(choices=[('seeds', '🌱 Toxumlar'), ('fertilizers', '🧪 Gübrələr'), ('pesticides', '🐛 Zəhərlər'), ('herbicides', '🌿 Herbisidlar'), ('equipment', '🔧 Avadanlıq'), ('tools', '🛠️ Alətlər'), ('spare_parts', '⚙️ Ehtiyat Hissələr'), ('fuel', '⛽ Yanacaq')], max_length=20, verbose_name='Kateqoriya')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdar')),
                ('unit', models.CharField(max_length=20, verbose_name='Vahid')),
                ('min_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum stok')),
                ('max_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum stok')),
                ('supplier_name', models.CharField(blank=True, max_length=100, verbose_name='Təchizatçı')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vahid qiyməti')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ümumi dəyər')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Son istifadə tarixi')),
                ('storage_location', models.CharField(blank=True, max_length=100, verbose_name='Saxlama yeri')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anbar məhsulu',
                'verbose_name_plural': 'Anbar məhsulları',
                'ordering': ['-created_at'],
            },
        ),
    ]
