# Generated by Django 5.2.7 on 2025-11-03 16:31

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, help_text='Məhsulun şəklini yükləyin (max 5MB)', null=True, upload_to=inventory.models.inventory_image_path, verbose_name='Şəkil'),
        ),
    ]
