# Generated by Django 5.2.7 on 2026-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='storage_location',
            field=models.CharField(blank=True, choices=[('main_warehouse', 'Əsas Anbar'), ('cold_storage', 'Soyuducu Anbar'), ('shelf_a', 'Rəf A'), ('shelf_b', 'Rəf B'), ('external', 'Xarici Sahə'), ('other', 'Digər')], default='main_warehouse', max_length=50, verbose_name='Saxlama yeri'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kiloqram (kg)'), ('g', 'Qram (g)'), ('l', 'Litr (l)'), ('ml', 'Millilitr (ml)'), ('pcs', 'Ədəd (pcs)'), ('boxes', 'Qutu (boxes)'), ('tons', 'Ton (tons)')], max_length=20, verbose_name='Vahid'),
        ),
    ]
