# Generated by Django 5.2.7 on 2026-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('slug', models.SlugField(unique=True, verbose_name='Link (Slug)')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Şəkil')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('is_published', models.BooleanField(default=True, verbose_name='Dərc edilib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
