# Generated by Django 5.2.7 on 2026-01-28 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0003_remove_field_irrigation_date_alter_field_user'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_date', models.DateField(default=django.utils.timezone.now, help_text='Sulama əməliyyatının planlaşdırıldığı tarix', verbose_name='Sulama tarixi')),
                ('irrigation_type', models.CharField(choices=[('drip', 'Damcıla sulama'), ('sprinkler', 'Yağış sulama'), ('flood', 'Sel sulama'), ('furrow', 'Sıra arası sulama')], max_length=20, verbose_name='Sulama növü')),
                ('water_volume_liters', models.DecimalField(decimal_places=2, help_text='Sulama üçün istifadə olunan suyun həcmi litrlərlə', max_digits=10, verbose_name='Su həcmi (litrlər)')),
                ('notes', models.TextField(blank=True, help_text='Sulama əməliyyatı ilə bağlı əlavə qeydlər', verbose_name='Qeydlər')),
                ('is_automated', models.BooleanField(default=False, help_text='Sulama əməliyyatının avtomatlaşdırılmış sistem tərəfindən idarə olunub-olunmadığını göstərir', verbose_name='Avtomatlaşdırılmış')),
                ('start_time', models.TimeField(blank=True, help_text='Sulama əməliyyatının başlama vaxtı (əgər avtomatlaşdırılıbsa)', null=True, verbose_name='Başlama vaxtı')),
                ('end_time', models.TimeField(blank=True, help_text='Sulama əməliyyatının bitmə vaxtı (əgər avtomatlaşdırılıbsa)', null=True, verbose_name='Bitmə vaxtı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_irrigation_records', to='fields.field')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_irrigation_records', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Suvarma',
                'verbose_name_plural': 'Suvarmalar',
                'ordering': ['-irrigation_date'],
            },
        ),
    ]
