# Generated by Django 5.2.7 on 2026-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationschedule',
            name='applied_fertilizer',
            field=models.CharField(blank=True, help_text='Əgər su ilə gübrə verilibsə qeyd edin', max_length=100, verbose_name='Verilən gübrə'),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='energy_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nasosun işlətdiyi elektrik enerjisi', max_digits=7, null=True, verbose_name='Enerji sərfi (kWh)'),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='soil_moisture_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suvarma başladığı andakı rütubət', max_digits=5, null=True, verbose_name='Torpaq rütubəti (%)'),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='status',
            field=models.CharField(choices=[('planned', 'Planlaşdırılıb'), ('active', 'Davam edir'), ('completed', 'Tamamlandı'), ('failed', 'Xəta')], default='completed', max_length=20),
        ),
    ]
