# Generated by Django 5.2.7 on 2026-01-31 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_remove_field_irrigation_date_alter_field_user'),
        ('irrigation', '0002_irrigationschedule_applied_fertilizer_and_more'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irrigationschedule',
            options={'ordering': ['-irrigation_date', '-start_time'], 'verbose_name': 'Suvarma', 'verbose_name_plural': 'Suvarmalar'},
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='applied_fertilizer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Verilən gübrə'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Bitmə vaxtı'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='energy_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Enerji sərfi (kWh)'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_irrigation_records', to='fields.field', verbose_name='Sahə'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='irrigation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sulama tarixi'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='irrigation_type',
            field=models.CharField(choices=[('drip', '💧 Damcıla suvarma'), ('sprinkler', '🚿 Yağışyağdırma'), ('pivot', '🎡 Pivot (Dairəvi)'), ('flood', '🌊 Sel (Arx) suvarma'), ('subsurface', '🚜 Torpaqaltı')], max_length=20, verbose_name='Sulama növü'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='is_automated',
            field=models.BooleanField(default=False, verbose_name='Avtomatlaşdırılmış'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Qeydlər'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_irrigation_records', to='plants.plant', verbose_name='Bitki'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='soil_moisture_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Torpaq rütubəti (%)'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Başlama vaxtı'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='status',
            field=models.CharField(choices=[('planned', 'Planlaşdırılıb'), ('active', 'Davam edir'), ('completed', 'Tamamlandı'), ('failed', 'Xəta')], default='completed', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='water_volume_liters',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Su həcmi (litrlər)'),
        ),
    ]
