# Generated by Django 5.2.7 on 2026-01-24 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0003_remove_field_irrigation_date_alter_field_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sensor adı')),
                ('sensor_code', models.CharField(max_length=50, unique=True, verbose_name='Sensor kodu')),
                ('sensor_type', models.CharField(choices=[('soil_moisture', '🌱 Torpaq Nəmliyi'), ('temperature', '🌡️ Temperatur'), ('humidity', '💧 Rütubət'), ('ph', '⚗️ pH Səviyyəsi'), ('nutrient', '🧪 Qida Maddələri'), ('light', '☀️ İşıq Intensivliyi'), ('rainfall', '🌧️ Yağış')], max_length=20, verbose_name='Sensor növü')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('installation_date', models.DateField(verbose_name='Qurulma tarixi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunluq')),
                ('battery_level', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Batareya səviyyəsi (%)')),
                ('data_interval', models.IntegerField(default=60, verbose_name='Məlumat intervalı (dəq)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Son texniki qulluq')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='fields.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensorlar',
                'ordering': ['-installation_date'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Dəyər')),
                ('unit', models.CharField(max_length=20, verbose_name='Vahid')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd tarixi')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Sensor məlumatı',
                'verbose_name_plural': 'Sensor məlumatları',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
