# Generated by Django 5.2.7 on 2026-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='irrigation_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
