# Generated by Django 5.2.7 on 2026-02-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_remove_field_irrigation_date_alter_field_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='ph_level',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3),
        ),
    ]
