# Generated by Django 5.2.7 on 2026-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_field_ph_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yer (şəhər)'),
        ),
    ]
